In [63]:
from tensorflow.keras.preprocessing.text import one_hot

In [64]:

###
sent =[ 'the glass of milk ',
        'the glass of juice',
        'the cup of tea',
        'I am a godd boy',
        'I am a good Developer',
        'understand the meaning of words',
        'your videos are good ',]

In [65]:
sent

['the glass of milk ',
 'the glass of juice',
 'the cup of tea',
 'I am a godd boy',
 'I am a good Developer',
 'understand the meaning of words',
 'your videos are good ']

In [66]:
# Define the vocabulary size
voc_size = 10000

In [67]:
#One Hot Representation
one_hot_repr = [one_hot(words ,voc_size) for words in sent]
one_hot_repr


[[7792, 5877, 6760, 2060],
 [7792, 5877, 6760, 2566],
 [7792, 6831, 6760, 7523],
 [9279, 4533, 7133, 8403, 3837],
 [9279, 4533, 7133, 587, 3473],
 [7639, 7792, 529, 6760, 1145],
 [4329, 8479, 3239, 587]]

In [68]:
## word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [69]:
import numpy as np

In [70]:
sent_lenght = 8
embedded_docs =pad_sequences(one_hot_repr,padding='pre', maxlen=sent_lenght)

In [71]:
print(embedded_docs)

[[   0    0    0    0 7792 5877 6760 2060]
 [   0    0    0    0 7792 5877 6760 2566]
 [   0    0    0    0 7792 6831 6760 7523]
 [   0    0    0 9279 4533 7133 8403 3837]
 [   0    0    0 9279 4533 7133  587 3473]
 [   0    0    0 7639 7792  529 6760 1145]
 [   0    0    0    0 4329 8479 3239  587]]


In [74]:
dim = 10 
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam','mse')


In [75]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step


array([[[ 0.02192681, -0.03364623, -0.03969133, -0.01090591,
         -0.04368131,  0.00567175, -0.00979328,  0.01936586,
         -0.03282328, -0.02543925],
        [ 0.02192681, -0.03364623, -0.03969133, -0.01090591,
         -0.04368131,  0.00567175, -0.00979328,  0.01936586,
         -0.03282328, -0.02543925],
        [ 0.02192681, -0.03364623, -0.03969133, -0.01090591,
         -0.04368131,  0.00567175, -0.00979328,  0.01936586,
         -0.03282328, -0.02543925],
        [ 0.02192681, -0.03364623, -0.03969133, -0.01090591,
         -0.04368131,  0.00567175, -0.00979328,  0.01936586,
         -0.03282328, -0.02543925],
        [-0.00685493,  0.01888135,  0.04711458,  0.01739523,
          0.01278386, -0.03507699, -0.01112828,  0.01611929,
          0.02166793,  0.00744266],
        [ 0.02775419,  0.00497157,  0.04915271, -0.03546333,
          0.04674014,  0.04004114,  0.02293989, -0.01220447,
          0.02622965, -0.03661373],
        [-0.04085002,  0.0161669 , -0.01345631, -0.0

: 

In [61]:
print(len(model.layers))


1


In [62]:
print(model.layers)

[<Embedding name=embedding_8, built=False>]
